site_name: SciEcon Blockchain + Symposium

theme: 
  name: material
  logo: assets/sciecon-b-l.jpg
  favicon: assets/sciecon-w.jpg
  font:
    # text: Playfair Display
  features:
    # - navigation.tabs
    # - navigation.top
    # - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tabs.sticky

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - "Program Overview": index.md 
  - "Symposium Slides": assets/SymposiumSlides.pdf
  - Articles:
    - "A Blockchain-based Decentralized Cloud Storage with “Keeper-and-Distributor” Systems": articles/1_josh.md